POSTGRES_DB:
  DB_DRIVER: pgx
  DB_HOST: 127.0.0.1
  DB_PORT: 5432
  DB_USER: auth_user
  DB_PASSWORD: auth_password
  DB_NAME: auth_db

REDIS_DB:
  HOST: 127.0.0.1
  PORT: 6379
  PASSWORD: redis_password
  DB: 0
